//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khamitova4432.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int FreeAppointmentId { get; set; }
        public int PatientId { get; set; }
        public int StatusId { get; set; }
    
        public virtual FreeAppointment FreeAppointment { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Status Status { get; set; }
    }
}
