//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khamitova4432.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicdbContext : DbContext
    {
        public medicdbContext()
            : base("name=medicdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<FreeAppointment> FreeAppointments { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<LabResult> LabResults { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TreatmentPlan> TreatmentPlans { get; set; }
    }
}
