//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khamitova4432.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabResult
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public System.DateTime DateOfResults { get; set; }
        public double SKF { get; set; }
        public double Glucose { get; set; }
        public double SystolicBloodPressure { get; set; }
        public double DiastolicBloodPressure { get; set; }
        public double BMI { get; set; }
        public double Hypertension { get; set; }
        public int Smoking { get; set; }
        public double Cholesterol { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
